server {
    listen 80;
    server_name milesvisual.duckdns.org;

    # Backend API
    location /api/ {
        proxy_pass http://localhost:3002/; # El '/' al final es clave para que /api/users pase a /users
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        
        # Ajustes de CORS si es necesario manejarlos en Nginx
        add_header 'Access-Control-Allow-Origin' '*' always;
    }

    # Frontend Next.js
    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
